(()=>{
'use strict';
const $=id=>document.getElementById(id), U=window.TS, IC=window.TSIcons;
let cfg=U.normalize(window.TONHOSOLO_DEFAULTS), tab='links', selected=-1, fb=null, user=null, live=false;
const editor=$('edit-content'), iconDialog=$('icon-backdrop');
const esc=U.esc;
const field=(key,label,type='text',placeholder='')=>`<label class="field"><span>${esc(label)}</span><input data-field="${key}" type="${type}" value="${esc(cfg[key]||'')}" placeholder="${esc(placeholder)}"></label>`;
const area=(key,label)=>`<label class="field"><span>${esc(label)}</span><textarea data-field="${key}" rows="3">${esc(cfg[key]||'')}</textarea></label>`;
const toast=(msg)=>{const node=$('toast');node.textContent=msg;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),3500)};
const icons=['link','whatsapp','instagram','facebook','youtube','tiktok','globe','phone','mail','map-pin','hammer','hard-hat','building','paintbrush','images','camera','calendar','file-text','star','shield-check','arrow-up-right','shopping-bag','message-circle','wrench','truck','house','check','download'];
function preview(){const f=$('site-preview');if(f?.contentWindow)f.contentWindow.postMessage({type:'TONHOSOLO_PREVIEW',payload:cfg},location.origin);$('save-status').textContent=live?'Alterações não publicadas':'Edição local';}
function rerender(){render();preview()}
const fields={links:['Links e ícones','Escolha os botões, ícones e destinos exibidos no seu perfil.'],conteudo:['Conteúdo','Edite os textos da página e os serviços apresentados.'],aparencia:['Aparência','Personalize a identidade visual e o logotipo.'],contato:['Contatos','Informe os seus canais oficiais de atendimento.'],configuracoes:['Configurações','Importe e exporte os dados do site.']};
function render(){
 document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
 $('tab-heading').textContent=fields[tab][0];$('tab-description').textContent=fields[tab][1];
 if(tab==='links'){
 editor.innerHTML=`<div class="section-bar"><h2>Seus links <small>(${cfg.links.length})</small></h2><button class="btn btn-primary" id="add-link">+ Adicionar link</button></div><p class="helper">Escolha o ícone, insira o endereço e use as setas para definir a ordem dos botões. Um link sem endereço aparecerá como “Em breve”.</p><div class="links-list">${cfg.links.map((l,i)=>`<div class="link-edit" data-index="${i}"><div class="link-edit-head"><button class="icon-picker" data-icon-index="${i}" title="Selecionar ícone">${IC.svg(l.icon||'link')}</button><div class="link-name"><strong>${esc(l.title||'Novo link')}</strong><small>${esc(l.subtitle||'Editar link')}</small></div><div class="link-controls"><button data-move="up" data-i="${i}" ${i===0?'disabled':''} title="Subir">↑</button><button data-move="down" data-i="${i}" ${i===cfg.links.length-1?'disabled':''} title="Descer">↓</button><button data-remove="${i}" title="Excluir">✕</button></div></div><div class="link-edit-fields"><label class="field">Título<input data-link="title" data-i="${i}" maxlength="75" value="${esc(l.title)}" placeholder="Ex.: Peça seu orçamento"></label><label class="field">Descrição<input data-link="subtitle" data-i="${i}" maxlength="110" value="${esc(l.subtitle)}"></label><label class="field">URL<input data-link="url" data-i="${i}" value="${esc(l.url)}" placeholder="https://..."></label><div class="link-toggles"><label><input type="checkbox" data-link="visible" data-i="${i}" ${l.visible?'checked':''}> Exibir na página</label><label><input type="checkbox" data-link="featured" data-i="${i}" ${l.featured?'checked':''}> Destacar botão</label></div></div></div>`).join('')}</div>`;
 }else if(tab==='conteudo'){
 editor.innerHTML=`<div class="edit-card"><h2>Apresentação</h2>${field('brand','Nome da empresa')}${field('handle','Nome de exibição / especialidade')}${field('eyebrow','Texto superior')}${field('heroTitle','Chamada principal')}${field('heroHighlight','Trecho destacado em dourado')}${area('description','Texto de apresentação')}${area('bio','Bio resumida')}</div><div class="edit-card"><h2>Serviços</h2>${cfg.services.map((s,i)=>`<div class="service-editor"><label class="field">Serviço ${i+1}<input data-service="title" data-i="${i}" value="${esc(s.title)}"></label><label class="field">Descrição<textarea data-service="description" data-i="${i}">${esc(s.description)}</textarea></label><button class="btn btn-subtle" data-service-remove="${i}">Remover serviço</button></div>`).join('')}<button class="btn btn-subtle" id="add-service">+ Adicionar serviço</button></div>`;
 }else if(tab==='aparencia'){
 editor.innerHTML=`<div class="edit-card"><h2>Identidade visual</h2><p class="helper">O logotipo original da Tonhosolo já está aplicado. Você pode substituí-lo por PNG, JPG ou WebP.</p><div class="logo-preview"><img src="${esc(cfg.logo)}" alt="Logotipo" style="max-width:200px;max-height:110px;object-fit:contain;background:#151515;padding:12px;border-radius:12px"></div><label class="field">Enviar logo<input type="file" id="logo-upload" accept="image/png,image/jpeg,image/webp"></label>${field('accent','Cor de destaque','color')}${field('background','Cor de fundo','color')}<button class="btn btn-subtle" id="reset-logo">Restaurar logo original</button></div>`;
 }else if(tab==='contato'){
 editor.innerHTML=`<div class="edit-card"><h2>Canais oficiais</h2><p class="helper">Preencha apenas os canais existentes. O WhatsApp pode ser digitado com DDD (ex.: 11999999999).</p>${field('whatsapp','WhatsApp com DDD','tel','11999999999')}${field('instagram','Instagram (URL ou @usuario)')}${field('email','E-mail comercial','email')}${field('location','Endereço no Google Maps (URL)')}</div>`;
 }else{
 editor.innerHTML=`<div class="edit-card"><h2>Publicação e backup</h2><p class="helper">Sem Firebase, as edições ficam neste navegador. Use “Baixar atualização” para exportar o arquivo defaults.js e substituí-lo no projeto antes do deploy. Com Firebase configurado e conta autorizada, “Publicar” disponibiliza as alterações online.</p><button class="btn btn-subtle" id="export-json">Exportar backup JSON</button> <button class="btn btn-subtle" id="import-json">Importar JSON</button><button class="btn btn-subtle" id="restore">Restaurar padrão</button><h2>SEO</h2>${field('seoTitle','Título para mecanismos de busca')}${area('seoDescription','Descrição da página')}</div>`;
 }
}
editor.addEventListener('input',e=>{const el=e.target;if(el.dataset.field){cfg[el.dataset.field]=el.value;preview()}if(el.dataset.link){const i=+el.dataset.i;cfg.links[i][el.dataset.link]=el.type==='checkbox'?el.checked:el.value;preview();if(el.dataset.link==='title'||el.dataset.link==='subtitle'){const row=el.closest('.link-edit');row.querySelector('.link-name strong').textContent=cfg.links[i].title||'Novo link';row.querySelector('.link-name small').textContent=cfg.links[i].subtitle||'Editar link'}}if(el.dataset.service){cfg.services[+el.dataset.i][el.dataset.service]=el.value;preview()}});
editor.addEventListener('change',async e=>{const el=e.target;if(el.id==='logo-upload'&&el.files[0]){if(el.files[0].size>1500000)return toast('Selecione uma imagem de até 1,5 MB.');const rd=new FileReader();rd.onload=()=>{cfg.logo=String(rd.result);rerender()};rd.readAsDataURL(el.files[0]);}else if(el.dataset.link){cfg.links[+el.dataset.i][el.dataset.link]=el.checked;preview()}});
editor.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.id==='add-link'){cfg.links.push({id:'link-'+Date.now(),title:'Novo link',subtitle:'',url:'',icon:'link',featured:false,visible:true});rerender();return}
 if(b.dataset.remove!==undefined){if(confirm('Remover este link?')){cfg.links.splice(+b.dataset.remove,1);rerender()}return}
 if(b.dataset.move){const i=+b.dataset.i,j=i+(b.dataset.move==='up'?-1:1);[cfg.links[i],cfg.links[j]]=[cfg.links[j],cfg.links[i]];rerender();return}
 if(b.dataset.iconIndex!==undefined){selected=+b.dataset.iconIndex;openIcons();return}
 if(b.id==='add-service'){if(cfg.services.length<8){cfg.services.push({title:'Novo serviço',description:''});rerender()}else toast('Limite de 8 serviços.');return}
 if(b.dataset.serviceRemove!==undefined){cfg.services.splice(+b.dataset.serviceRemove,1);rerender();return}
 if(b.id==='reset-logo'){cfg.logo='./assets/logo-tonhosolo.png';rerender();return}
 if(b.id==='export-json'){download('tonhosolo-backup.json',JSON.stringify(cfg,null,2),'application/json');return}
 if(b.id==='import-json'){$('import-file').click();return}
 if(b.id==='restore'){if(confirm('Restaurar os dados originais?')){cfg=U.normalize(window.TONHOSOLO_DEFAULTS);rerender()}return}
});
function openIcons(){$('icon-grid').innerHTML=icons.map(icon=>`<button class="icon-choice" type="button" data-choice="${icon}" title="${icon}">${IC.svg(icon)}<small>${icon}</small></button>`).join('');iconDialog.classList.remove('hidden')}
$('icon-grid').addEventListener('click',e=>{const b=e.target.closest('[data-choice]');if(!b)return;cfg.links[selected].icon=b.dataset.choice;iconDialog.classList.add('hidden');rerender()});
$('close-icon').addEventListener('click',()=>iconDialog.classList.add('hidden'));
iconDialog.addEventListener('click',e=>{if(e.target===iconDialog)iconDialog.classList.add('hidden')});
function download(name,content,type='text/javascript'){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)}
function exportJs(){download('defaults.js','window.TONHOSOLO_DEFAULTS = '+JSON.stringify(cfg,null,2)+';\n') ;toast('Arquivo defaults.js baixado. Substitua o anterior no projeto e publique novamente.')}
$('download-config').addEventListener('click',exportJs);
$('publish').addEventListener('click',async()=>{if(!live)return exportJs();if(!user)return toast('Faça login para publicar.');try{$('publish').disabled=true;await fb.store.setDoc(fb.store.doc(fb.db,'sitePages',fb.id),{content:U.normalize(cfg),updatedAt:fb.store.serverTimestamp(),updatedBy:user.uid});$('save-status').textContent='Publicado agora';toast('Alterações publicadas!')}catch(err){toast('Não foi possível publicar: '+(err.code||err.message))}finally{$('publish').disabled=false}});
$('import-file').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{cfg=U.normalize(JSON.parse(await f.text()));rerender();toast('Backup importado. Confira a prévia antes de publicar.')}catch{toast('Arquivo JSON inválido.')}e.target.value=''});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;rerender()}));
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===$('site-preview').contentWindow&&e.data?.type==='TONHOSOLO_PREVIEW_READY')preview()});
async function init(){if(!window.TONHOSOLO_FIREBASE){render();preview();return}try{fb=await U.connectFirebase();if(!fb){render();return}live=true;$('status-title').textContent='Firebase conectado';$('status-desc').textContent='Requer administrador autorizado';$('publish-label').textContent='Publicar alterações';$('auth-backdrop').classList.remove('hidden');fb.auth.onAuthStateChanged(fb.authorization,async u=>{user=u;if(!u){$('auth-backdrop').classList.remove('hidden');return}try{const perm=await fb.store.getDoc(fb.store.doc(fb.db,'siteAdmins',u.uid));if(!perm.exists()||perm.data().enabled!==true){await fb.auth.signOut(fb.authorization);$('login-error').textContent='Esta conta não tem permissão de administrador.';return}const page=await fb.store.getDoc(fb.store.doc(fb.db,'sitePages',fb.id));if(page.exists()&&page.data().content)cfg=U.normalize(page.data().content);$('auth-backdrop').classList.add('hidden');$('logout').classList.remove('hidden');rerender()}catch(err){$('login-error').textContent='Falha ao verificar autorização: '+(err.code||err.message);await fb.auth.signOut(fb.authorization)}});
 $('auth-form').addEventListener('submit',async e=>{e.preventDefault();$('login-error').textContent='';try{await fb.auth.signInWithEmailAndPassword(fb.authorization,$('login-email').value,$('login-password').value)}catch(err){$('login-error').textContent='Não foi possível entrar: '+(err.code||err.message)}});$('logout').addEventListener('click',()=>fb.auth.signOut(fb.authorization));
 }catch(err){toast('Falha ao conectar Firebase. Configuração local ativa.');live=false}render();preview()}
init();
})();
